config/routes.rb
JQueryAutocompleteSample::Application.routes.draw do
  resources :manufacturers

  resources :colors

  resources :products

  resources :categories

  
  root :to => "products#index"

end

app/models/color.rb
class Color < ActiveRecord::Base
  has_many :products
  #CHANGES_HERE
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  # GET /colors
  # GET /colors.xml
  def index
    if params[:term] #CHANGES_HERE
      @colors = Color.where("name LIKE ?", "%#{params[:term]}%")
    else
      @colors = Color.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.js #CHANGES_HERE
      format.xml  { render :xml => @colors }
    end
  end

  # GET /colors/1
  # GET /colors/1.xml
  def show
    @color = Color.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @color }
    end
  end

  # GET /colors/new
  # GET /colors/new.xml
  def new
    @color = Color.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @color }
    end
  end

  # GET /colors/1/edit
  def edit
    @color = Color.find(params[:id])
  end

  # POST /colors
  # POST /colors.xml
  def create
    @color = Color.new(params[:color])

    respond_to do |format|
      if @color.save
        format.html { redirect_to(@color, :notice => 'Color was successfully created.') }
        format.xml  { render :xml => @color, :status => :created, :location => @color }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @color.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /colors/1
  # PUT /colors/1.xml
  def update
    @color = Color.find(params[:id])

    respond_to do |format|
      if @color.update_attributes(params[:color])
        format.html { redirect_to(@color, :notice => 'Color was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @color.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /colors/1
  # DELETE /colors/1.xml
  def destroy
    @color = Color.find(params[:id])
    @color.destroy

    respond_to do |format|
      format.html { redirect_to(colors_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/views/colors/_form.html.erb
<%= form_for(@color) do |f| %>
  <% if @color.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@color.errors.count, "error") %> prohibited this color from being saved:</h2>

      <ul>
      <% @color.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colors/edit.html.erb
<h1>Editing color</h1>

<%= render 'form' %>

<%= link_to 'Show', @color %> |
<%= link_to 'Back', colors_path %>

app/views/colors/index.html.erb
<h1>Colors</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @colors.each do |color| %>
  <tr>
    <td><%= color.name %></td>
    <td><%= link_to 'Show', color %></td>
    <td><%= link_to 'Edit', edit_color_path(color) %></td>
    <td><%= link_to 'Destroy', color, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Color', new_color_path %>

app/views/colors/index.js.erb
[
<% @colors.each do |color| %>
	"<%= color.name %>", 
<% end %>
]

app/views/colors/new.html.erb
<h1>New color</h1>

<%= render 'form' %>

<%= link_to 'Back', colors_path %>

app/views/colors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @color.name %>
</p>


<%= link_to 'Edit', edit_color_path(@color) %> |
<%= link_to 'Back', colors_path %>